### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by HrBjarup** [MalteMagnussen/CA2-FrontEnd#2]
~~Create Travis pipeline~~

~~Remove Travis pipeline. We use surge instead.~~

Camilla pointed out we might get it to work via: https://docs.travis-ci.com/user/deployment/surge/

**Comment by Castau** [comment]
![image](https://user-images.githubusercontent.com/35559774/66639891-19ef6380-ec18-11e9-8999-b67b2694396e.png)

**Comment by MalteMagnussen** [comment]
We have to use surge instead.
