### ISSUE TITLE
Move useful stuff from html pages in backend project over to this one. 

### ISSUE THREAD

**Issue by MalteMagnussen** [MalteMagnussen/CA2-FrontEnd#23]
- [x] ScrumPage - #31 

Don't delete the old stuff in the backend project though. It is quite handy to have the easy links to API etc.

**Comment by Runi-VN** [comment]
I believe this is done, right? Only other thing to add would be a link back to our backend page.

**Comment by MalteMagnussen** [comment]
Yeah. Maybe we want some of the stuff in the index, though? Isn't it nice to have the links to API and GitHub?

**Comment by Castau** [comment]
I can fix this in along with the styling issue
