### ISSUE TITLE
We need a working url for the frontend

### ISSUE THREAD

**Issue by Castau** [MalteMagnussen/CA2-FrontEnd#48]
It is fine with a surge address we can deploy to manually, but it has to be done before sunday.

**Comment by Runi-VN** [comment]
Once done:  
Remember to update the frontend link in the document below as required:
https://docs.google.com/spreadsheets/d/1M1Txexm5BwBe9F2YWi0vNrKm-9gFTbKebwH0f8zQJzM/edit#gid=0

**Comment by Castau** [comment]
It has been done! :D
